apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-cm
  labels:
    app: vault
data:
  vault.addr: "http://0.0.0.0:8200"
  local.config: |
    {
      "ui": true,
      "listener": [{
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": true
        }
      }],
      "storage": [{
        "file": {
          "path": "/vault/backend-file-storage"
        }
      }]
    }
