apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  labels:
    app: vault
    type: local
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/vault-storage/
  storageClassName: manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vault-pvc
  labels:
    app: vault
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: vault
      type: local
  storageClassName: manual
